#!/bin/bash
# clone original youtube-dl
git clone --depth=1 https://github.com/ytdl-org/youtube-dl.git bloat
cd bloat
# apply our patch with tweaks
git apply "../patches/minimize.patch"
# do things that a small patch can't
cd youtube_dl/extractor
mkdir tmp
mv __init__.py common.py commonmistakes.py commonprotocols.py youtube.py tmp
rm *.py
mv tmp/* .
cp ../../../patches/extractors.py .
rm -rf tmp
cd ../..
# build our version
make
mv youtube-dl ../ytd
cd ..
rm -rf bloat
## and install
sudo install ytd /usr/local/bin
rm ytd
